initiateExelaExtractDateRange method added to DataExtractServiceImpl.
hmcts/probate-orchestrator-service pull request #450
Opened 2021-02-12 10:30 UTC by stelioskalo

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/DTSPB-1380

### Change description ###
Created API that will allow a date range to be used when sending data to Excela.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2021-02-15 15:49 UTC, sanjayparekh-hmcts requested changes

2021-02-15 15:49 UTC, sanjayparekh-hmcts commented on src/main/java/uk/gov/hmcts/probate/client/backoffice/BackOfficeApi.java
> +            @RequestParam(value = "fromDate", required = false) String fromDate,
These probably need to be req = true

2021-02-17 14:20 UTC, stelioskalo commented on src/main/java/uk/gov/hmcts/probate/client/backoffice/BackOfficeApi.java
> +            @RequestParam(value = "fromDate", required = false) String fromDate,
done

2021-02-19 10:30 UTC, elvianihuseyin approved these changes
LGTM

2021-03-03 17:23 UTC, sanjayparekh-hmcts approved these changes

2021-03-03 17:24 UTC, merged